# Streamlit Secrets Configuration
# Copy this file and replace the placeholder values with your actual API keys

# OpenAI API Key
OPENAI_API_KEY = "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"

# Pushover Configuration (for notifications)
PUSHOVER_USER = "uevdzfz1mgwbkidcm5kya8osvzrfv2"
PUSHOVER_TOKEN = "a7g9rwizz34kn4xoub865tyryhkgzf"
